version: "3"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - PG_PASSWORD=password
      - PG_DB=gcb_db
      - PG_USER=postgres
      - PG_HOST=db
    volumes:
      - ".:/code"

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gcb_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
