version: "3"

services:
  db:
    image: postgres:14
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gcb_db

  app:
    build: .
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    ports:
      - 3000:3000
    environment:
      - PG_PASSWORD=password
      - PG_DB=gcb_db
      - PG_USER=postgres
      - PG_HOST=db
    volumes:
      - ".:/code"
